# Generated by Django 4.2.3 on 2023-07-19 11:45

from django.db import migrations, models
import userauths.models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0002_profile_bio_profile_created_profile_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to=userauths.models.user_directory_path, verbose_name='Picture'),
        ),
    ]
