# Generated by Django 4.2.3 on 2023-08-09 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0004_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2023-08-09 16:36:00'),
            preserve_default=False,
        ),
    ]
