# Generated by Django 4.2.3 on 2023-07-24 13:01

from django.db import migrations, models
import post.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='likes',
            name='is_liked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='picture',
            field=models.ImageField(default='', upload_to=post.models.user_directory_path, verbose_name='Picture'),
            preserve_default=False,
        ),
    ]
