# Generated by Django 4.2.3 on 2023-07-24 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_likes_is_liked_alter_post_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_liked_by_user',
            field=models.BooleanField(default=False),
        ),
    ]
