# Generated by Django 4.2.3 on 2023-07-24 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_post_is_liked_by_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_liked_by_user',
        ),
    ]
