# Generated by Django 4.2.3 on 2023-07-24 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_remove_post_is_liked_by_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
